services:
  video_parser:
    build: .
    environment:
      OPENAI_API_KEY: your_openai_api_key
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: your_neo4j_password
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: neo4j/your_neo4j_password
    ports:
      - 7687:7687
      - 7474:7474